version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      # Ne mappe pas le répertoire vendor depuis l'hôte
      # - ./vendor:/var/www/html/vendor
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: casino_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
