# docker-compose.yml
version: '3.9'

services:
  web:
    build: .
    container_name: my_php_app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${WEB_PORT}"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      # Ne mappe pas le répertoire vendor depuis l'hôte pour des raisons de sécurité
      # - ./vendor:/var/www/html/vendor
    networks:
      - app_network

networks:
  app_network:
    external: true
