# docker-compose-db.yml
version: '3.9'  # Mettre à jour la version

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: super_secure_root_password
      MYSQL_DATABASE: casino_db
      MYSQL_USER: casino_user
      MYSQL_PASSWORD: super_secure_user_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=caching_sha2_password  # Utiliser le plugin recommandé
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    external: true

volumes:
  db_data:
